name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install xmake
      run: sudo add-apt-repository ppa:xmake-io/xmake && sudo apt update && sudo apt install xmake
    - name: make
      run: xmake
